### ISSUE TITLE
Tutorial Funky

### ISSUE THREAD

**Issue by ABWUPHBAWUIPAWBIUFAWIOF** [futzumi/Blooket-Hacks#2]
I dont really understand it that could just because I'm dumb and tired but I don't really know what you mean by copy what you want because this other hacks I had I just copy and pasted a bookmarklet code for all of them (also a GUI would be really cool)

sorry again

**Comment by futzumi** [comment]
@ABWUPHBAWUIPAWBIUFAWIOF I'm working on a UI. That's why the hacks aren't copy and pasteable already, becayuse thr UI will be. As for the tutorial, Copy the text inside the file of the hack you want, open a text editor, type "javascript:" before the text you copied. then you paste it
